from typing import List, Dict, Any
import logging
from .base import ChannelAdapter
from .types import CanonicalMessage, MediaItem, MediaType

logger = logging.getLogger(__name__)

class YCloudAdapter(ChannelAdapter):
    """
    Adapter para normalizar webhooks de YCloud (WhatsApp Business API).
    """

    async def normalize_payload(self, payload: Dict[str, Any], tenant_id: int) -> List[CanonicalMessage]:
        # YCloud Webhook Structure:
        # { "type": "message", "message": { ... } }
        # OR { "statuses": [...] } -> Ignored here
        
        event_type = payload.get("type")
        if event_type != "message":
            return []
            
        msg = payload.get("message", {})
        if not msg:
            return []
            
        # 1. Extraer Datos Básicos
        # YCloud sends "from" as the user phone number
        external_user_id = msg.get("from")
        
        # 2. Extraer Contenido
        msg_type = msg.get("type")
        content = ""
        media_items = []
        
        if msg_type == "text":
            content = msg.get("text", {}).get("body", "")
            
        elif msg_type == "image":
            img_data = msg.get("image", {})
            content = img_data.get("caption", "")
            media_items.append(MediaItem(
                type=MediaType.IMAGE,
                url=img_data.get("link"),
                mime_type=img_data.get("mime_type"),
                meta={"scanner_id": img_data.get("id")}
            ))
            
        elif msg_type == "audio" or msg_type == "voice":
            # Fix Audio WhatsApp: YCloud distingue audio (files) de voice (ptt)
            audio_data = msg.get("audio") or msg.get("voice", {})
            media_items.append(MediaItem(
                type=MediaType.AUDIO,
                url=audio_data.get("link"),
                mime_type=audio_data.get("mime_type"),
                meta={"voice": (msg_type == "voice")}
            ))
            
        elif msg_type == "document":
            doc_data = msg.get("document", {})
            content = doc_data.get("caption", "")
            media_items.append(MediaItem(
                type=MediaType.DOCUMENT,
                url=doc_data.get("link"),
                file_name=doc_data.get("filename") or "document",
                mime_type=doc_data.get("mime_type")
            ))
            
        elif msg_type == "button":
            content = msg.get("button", {}).get("text", "")
            
        elif msg_type == "interactive":
            interactive = msg.get("interactive", {})
            if interactive.get("type") == "button_reply":
                content = interactive.get("button_reply", {}).get("title", "")
            elif interactive.get("type") == "list_reply":
                content = interactive.get("list_reply", {}).get("title", "")
        
        # 3. Construir Canonical
        canonical = CanonicalMessage(
            provider="ycloud",
            original_channel="whatsapp",
            external_user_id=external_user_id,
            tenant_id=tenant_id,
            content=content,
            media=media_items,
            is_agent=False, # Webhook events are usually ONLY user messages (unless generated by system?)
            raw_payload=payload
        )
        
        self._log_normalization("YCloud", 1, [str(m.type) for m in media_items])
        return [canonical]
