UPDATE treatment_types SET ai_response_template = E'Muchas personas nos consultan en situaciones similares, sobre todo cuando perdieron dientes o están buscando una solución más cómoda y estable. La Dra. Laura Delgado se especializa en rehabilitación oral con implantes y prótesis, incluyendo casos complejos.\n\nPara orientarte mejor: ¿Cuál de estas situaciones se parece más a la tuya?\n• Perdí un diente\n• Perdí varios dientes\n• Uso prótesis removible\n• Necesito cambiar una prótesis\n• Tengo una prótesis que se mueve\n• No estoy seguro/a' WHERE tenant_id = 1 AND code IN ('implante_simple_risa', 'implante_complejo_cima', 'implante_guiado_tomo');

UPDATE treatment_types SET ai_response_template = E'La Dra. Laura Delgado se especializa en rehabilitación oral con prótesis e implantes, buscando soluciones funcionales, estables y planificadas según cada caso.\n\nPara orientarte mejor, contame por favor cuál de estas opciones se parece más a tu caso:\n• Necesito una prótesis nueva\n• Quiero cambiar una prótesis que ya uso\n• Mi prótesis se mueve\n• Me falta una parte dentaria y quiero rehabilitarla\n• No estoy seguro/a\n\nLo ideal es realizar una evaluación para ver qué tipo de rehabilitación te conviene más.' WHERE tenant_id = 1 AND code IN ('rehabilitacion_simple', 'rehabilitacion_compleja', 'rehabilitacion_integral');

UPDATE treatment_types SET ai_response_template = E'En estos casos es importante evaluar si se trata de terceros molares retenidos, la posición del diente y el tipo de procedimiento indicado.\n\nLa Dra. Laura Delgado atiende cirugía maxilofacial y extracción de muelas de juicio, incluyendo casos que requieren una planificación más precisa.\n\nSi hay dolor, inflamación o dificultad para abrir la boca, es importante evaluarlo para indicar la conducta adecuada.' WHERE tenant_id = 1 AND code IN ('cirugia_simple', 'cirugia_compleja');

UPDATE treatment_types SET ai_response_template = E'La armonización facial se trabaja de forma personalizada, buscando resultados naturales y acordes a cada rostro, siempre desde un criterio médico.\n\nSi querés, contame qué te gustaría mejorar o te ayudo directamente a coordinar una evaluación.' WHERE tenant_id = 1 AND code IN ('estetica_facial_simple', 'estetica_facial_avanzada', 'consulta_armonizacion_facial');

UPDATE treatment_types SET ai_response_template = E'Sí, realizamos evaluación para endolifting. Es un tratamiento que debe indicarse de forma personalizada, según la zona a tratar y el resultado esperado.\n\nSi querés, te ayudo a coordinar una consulta para valoración con la Dra.' WHERE tenant_id = 1 AND code = 'endolifting';

UPDATE treatment_types SET ai_response_template = E'Sí, te podemos ayudar con eso desde el equipo odontológico. Si querés, te coordino un turno con el profesional indicado según tu caso.' WHERE tenant_id = 1 AND code IN ('limpieza_dental', 'blanqueamiento_dental', 'restauracion_simple', 'restauracion_compleja');

UPDATE treatment_types SET ai_response_template = E'Sí, contamos con atención de ortodoncia a través del equipo. Si querés, te ayudo a coordinar una evaluación para indicarte el profesional adecuado.' WHERE tenant_id = 1 AND code IN ('consulta_ortodoncia', 'control_ortodoncia');

UPDATE treatment_types SET ai_response_template = E'Sí, este tipo de tratamiento lo realiza el equipo odontológico. Si querés, te ayudo a coordinar un turno para evaluación y derivación con el profesional indicado.' WHERE tenant_id = 1 AND code = 'endodoncia';

UPDATE treatment_types SET ai_response_template = E'La regeneración ósea es un procedimiento que se realiza previo o simultáneo a la colocación de implantes, para asegurar una base sólida y un resultado duradero.\n\nLa Dra. Laura Delgado se especializa en este tipo de procedimientos. Lo ideal es realizar una evaluación para ver el estado del hueso y planificar correctamente.' WHERE tenant_id = 1 AND code = 'injerto_regeneracion_osea';

UPDATE treatment_types SET ai_response_template = E'La Dra. Laura Delgado se especializa en rehabilitación oral con implantes, prótesis y planificación de casos complejos. Muchos pacientes que estaban en situaciones similares lograron volver a comer con normalidad, dejar la prótesis removible y sentirse más seguros.\n\nLo ideal en estos casos es hacer una evaluación para indicarte cuál es la mejor solución para vos.' WHERE tenant_id = 1 AND code = 'consulta_rehabilitacion_integral';

UPDATE treatment_types SET ai_response_template = E'Te ayudamos a coordinar un control con el profesional indicado según tu caso para evaluar el estado de tus tratamientos previos.' WHERE tenant_id = 1 AND code = 'control_revision';
