"""Sync point with patients and treatments

Revision ID: 820dbf12532d
Revises: 83ffa6090043
Create Date: 2026-03-10 23:44:30.010326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '820dbf12532d'
down_revision: Union[str, Sequence[str], None] = '83ffa6090043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. First, define the unique constraint on the target table
    op.create_unique_constraint('treatment_types_tenant_id_code_key', 'treatment_types', ['tenant_id', 'code'])
    
    # 2. Then, create the table that references those columns
    op.create_table('treatment_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('treatment_code', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'treatment_code'], ['treatment_types.tenant_id', 'treatment_types.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 3. Other operations
    op.drop_constraint(op.f('credentials_tenant_id_name_key'), 'credentials', type_='unique')
    op.create_foreign_key(None, 'credentials', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    
    op.alter_column('lead_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lead_notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lead_status_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('meta_form_leads', 'preferred_time',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='(COALESCE(preferred_date, CURRENT_DATE) + preferred_time)::timestamp with time zone')
    op.alter_column('meta_form_leads', 'converted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('meta_form_leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('meta_form_leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('patients', 'birth_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Fecha de nacimiento del paciente (formato DD/MM/AAAA)',
               existing_nullable=True)
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email del paciente para comunicación',
               existing_nullable=True)
    op.alter_column('patients', 'first_touch_source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Fuente de adquisición del paciente: ORGANIC, INSTAGRAM, GOOGLE, REFERRED, OTHER',
               existing_nullable=True,
               existing_server_default=sa.text("'ORGANIC'::character varying"))
    op.alter_column('patients', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Ciudad/Barrio del paciente para registro de admisión',
               existing_nullable=True)
    op.drop_column('users', 'test_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_column', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint('treatment_types_tenant_id_code_key', 'treatment_types', type_='unique')
    op.alter_column('patients', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment='Ciudad/Barrio del paciente para registro de admisión',
               existing_nullable=True)
    op.alter_column('patients', 'first_touch_source',
               existing_type=sa.VARCHAR(length=50),
               comment='Fuente de adquisición del paciente: ORGANIC, INSTAGRAM, GOOGLE, REFERRED, OTHER',
               existing_nullable=True,
               existing_server_default=sa.text("'ORGANIC'::character varying"))
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email del paciente para comunicación',
               existing_nullable=True)
    op.alter_column('patients', 'birth_date',
               existing_type=sa.DATE(),
               comment='Fecha de nacimiento del paciente (formato DD/MM/AAAA)',
               existing_nullable=True)
    op.alter_column('meta_form_leads', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('meta_form_leads', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('meta_form_leads', 'converted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('meta_form_leads', 'preferred_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.alter_column('lead_status_history', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lead_notes', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lead_notes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'credentials', type_='foreignkey')
    op.create_unique_constraint(op.f('credentials_tenant_id_name_key'), 'credentials', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_table('treatment_images')
    # ### end Alembic commands ###
