"""Medical guardrail helpers for test assertions.

Provides regex-based patterns that detect actual medical advice (dosing
instructions, drug prescriptions, diagnostic statements) generated by the
formatter. These replace brittle substring checks for words like "peligroso"
that also appear legitimately in the formatter's safety-instruction text
(e.g. "NUNCA decir que algo 'es peligroso'").

Usage:
    from tests.helpers.medical_guardrails import assert_no_medical_advice

    assert_no_medical_advice(formatter_output)
"""

import re

# Each pattern targets a concrete medical advice construct: dosing, prescribing,
# diagnostic statements. They do NOT match words that appear inside
# quoted examples within safety instructions (e.g. "NUNCA decir 'es peligroso'").
DANGEROUS_MEDICAL_PATTERNS: list[re.Pattern] = [
    # Drug names with dosing verb (tom[áa], tomés, tomar)
    re.compile(
        r"\btom[áae]s?\b.{0,30}\b(ibuprofeno|paracetamol|amoxicilina|antibi[óo]tico|aspirina|clindamicina|metronidazol)\b",
        re.IGNORECASE,
    ),
    # Dosing quantities: "Xmg cada Y horas"
    re.compile(r"\b\d+\s*mg\b.{0,20}\bcada\s+\d", re.IGNORECASE),
    # Prescribing verbs: "te receto", "recetamos", "recetá"
    re.compile(r"\brecet[oaé]\b", re.IGNORECASE),
    # "suspender la medicación" — instruction to change medication
    re.compile(r"\bsuspender\b.{0,20}\bmedicaci[óo]n\b", re.IGNORECASE),
    # "la diabetes impide el tratamiento" — false diagnostic conclusion
    re.compile(r"\b(la\s+diabetes|el\s+diabetes)\s+impide\b", re.IGNORECASE),
    # Absolute contraindication statements: "está contraindicado para X pacientes"
    re.compile(
        r"\bcontraindicado\s+(para|en)\s+(pacientes|embarazadas|niños)\b",
        re.IGNORECASE,
    ),
    # "no debes [tomar|hacer|continuar]" — direct prohibition to patient
    re.compile(r"\bno\s+deb[eé]s\s+(tomar|hacer|continuar|usar)\b", re.IGNORECASE),
    # "imposible para pacientes con" — absolute gatekeeping
    re.compile(r"\bimposible\s+para\s+pacientes\s+con\b", re.IGNORECASE),
    # "no apto para" — absolute exclusion claim
    re.compile(r"\bno\s+apto\s+para\b", re.IGNORECASE),
]


def assert_no_medical_advice(text: str, context: str = "") -> None:
    """Assert that *text* contains no actual medical advice patterns.

    Raises AssertionError with the matched pattern and excerpt if any
    DANGEROUS_MEDICAL_PATTERNS fires against the text.

    Args:
        text: The string to validate (formatter output or full prompt).
        context: Optional label included in the failure message.
    """
    label = f"[{context}] " if context else ""
    for pattern in DANGEROUS_MEDICAL_PATTERNS:
        match = pattern.search(text)
        if match:
            excerpt = text[max(0, match.start() - 30): match.end() + 30]
            raise AssertionError(
                f"{label}Medical advice pattern '{pattern.pattern}' matched.\n"
                f"Excerpt: ...{excerpt!r}..."
            )
